### ISSUE TITLE
patch face in documentary transcript not displayed---reappearing bug?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#14]
The transcription of the patch face is generally not visible in the documentary transcript. Example:
http://beta.faustedition.net/documentViewer.php?faustUri=faust://xml/document/faust/2.3/gsa_391473.xml&page=5&view=facsimile_document

I think that is a bug that appeared earlier and had already been fixed by Chleij?

**Comment by thvitt** [comment]
[relevant JS snippet in the Faust app](https://github.com/faustedition/faust-app/blob/master/faust/src/main/static/js/faust/transcript/transcript-interaction.js#L186)

**Comment by thvitt** [comment]
Ah, the previous version of the SVG generation appearently did not incude the patch's content at all. Current one does, we just need the interaction now.

Is this how it is supposed to look like _when hovering the patch_?

![Patch that is hovered](https://cloud.githubusercontent.com/assets/1906208/10883487/9655ad9a-8172-11e5-823a-669c98e4c362.png)

**Comment by gerritbruening** [comment]
Yes, this is how it was supposed to look like.
One could argue that things would become clearer if only one of them, either the patch-face or the underlying page is displayed.

**Comment by thvitt** [comment]
The simple CSS based solution does not really work:
```css
svg.diplomatic .element-patch:hover, svg.diplomatic .element-patch:hover * {
  opacity: 0.2 !important;
}
```
tunes down the patch `<rect>` on hover, letting the covered text appear rather unobstructed, but it does not have any effect on the text that is written _on_ the text, effectively showing both texts printed on each other. An additional rule,
```css
svg.diplomatic .element-patch:hover * {
  fill: red !important;
  stroke: green !important;
}
```
does not style the text _on hover_ (while working when not using the `:hover` pseudoclass!).

So I guess the solution is adding rules for sth like `.element-patch.transparent-patch` and adding / removing the `transparent-patch` class via JS.
