### ISSUE TITLE
Integrate additional images

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-web#204]
Es gibt mehr als eine Abbildung pro Seite:

* Zettel
* Kontrastverstärkende Aufnahmen

Kodierung über Faksimile-Elemente im dokumentarischen Transkript

* Erstmal nur Zettel?

* [ ] @gerritbruening identifiziere exemplarische Items, unten auflisten

**Comment by gerritbruening** [comment]
Immediate aim is to integrate the recto images of patches.

**Comment by gerritbruening** [comment]
Überblick auflisten.

**Comment by thvitt** [comment]
Die Digitalisate sind bereits vorhanden und auch konvertiert. Die Daten werden bei der JSON-Konvertierung auch extrahiert (unten mal als YAML), man sieht hier dass `page.doc[2].img` zwei Einträge hat, deren erster bereits jetzt angezeigt wird, die anderen sind Alternativen. 

Die Implementierung muss also eigentlich nur noch im documentViewer erfolgen.

```yaml
  - base: transcript/gsa/391473/
    document: faust/2.3/gsa_391473.xml
    page:
      - doc:
          - img:
              - gsa/391473/391473_0002
            imgLink: 8e7d8e9b-00df-48c0-9fdd-0db566c86fdc.svg
            uri: 0002.xml
        empty: false
      - doc:
          - {}
        empty: true
      - doc:
          - img:
              - gsa/391473/391473_0004
              - gsa/391473/391473_0003
            imgLink: d6421441-acb3-46a9-8b27-72f001e846ef.svg
            uri: 0004.xml
        empty: false
      - doc:
          - {}
        empty: false
      - doc:
          - img:
              - gsa/391473/391473_0006
              - gsa/391473/391473_0007
              - gsa/391473/391473_0005
            imgLink: 51b097d0-c177-4743-bc4f-93b69a7bfce9.svg
            uri: 0006.xml
        empty: false
```
